/**
 * GET /api/agent-stats
 *
 * Counters of the x402 payments received by the fee wallet, for the "AI Agents"
 * section.
 *
 * Source: asset transfers read from the chain — see src/lib/chain-activity.ts.
 *
 * WHAT IS COUNTED, AND WHY THERE ARE TWO NUMBERS
 * Promise P2 (hash-pinned, public/promises/P2-honest-counters.json) states that
 * the public counters are CUMULATIVE SINCE LAUNCH and INCLUDE the operator's own
 * wallets, and that the list of those wallets is published so that a third party
 * can reproduce the split between internal and external activity. Therefore:
 *   - `total_*` stays cumulative and includes the internal wallets: changing it
 *     would falsify a promise already anchored on-chain (it would require a P2
 *     v2 with a new promiseId).
 *   - `organic` is that split, computed here instead of left to the reader.
 * The list of internal wallets is read FROM THE PROMISE FILE rather than copied:
 * one single source, and the counts follow the file if it changes.
 */

import { inboundTokenPayments, USDC_BASE, FEE_WALLET } from '@/lib/chain-activity';
import { redactSecrets } from '@/lib/x402-helpers';
import promise from '../../../../public/promises/P2-honest-counters.json';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const OUR_WALLETS = new Set(
  (promise.our_wallets ?? []).map((w: string) => w.toLowerCase()),
);

// ─── In-memory cache ─────────────────────────────────────────────────────────
const CACHE_TTL_MS = 5 * 60 * 1_000;
const ERROR_CACHE_TTL_MS = 30_000;
let cache: { data: AgentStats; fetchedAt: number } | null = null;

interface Split {
  paid_calls: number;
  unique_agents: number;
  usdc: number;
}

/** Recent activity of external payers only: what the home page shows as "today" and "last call". */
interface OrganicRecent {
  /** Time of the latest payment from a wallet outside promise P2's list. */
  last_payment_at: string | null;
  /**
   * Times of the external payments of the last 48 hours, newest first — times only, no addresses.
   * The reader counts "today" in its own time zone, which a server-side UTC count would get wrong.
   */
  payment_times_48h: string[];
}

/**
 * Free use of the hosted MCP server, read from its public counter (/mcp/usage on the Worker).
 * `tool_calls` counts tools/call, resources/read and prompts/get: actual use, not the session
 * handshakes and tool listings that registry crawlers send. The counter has no caller identity,
 * so our own checks are included; days are UTC days.
 */
export interface FreeMcpUsage {
  tool_calls_total: number;
  tool_calls_today: number;
  sessions_today: number;
  counted_since: string;
  /** First UTC day of the current run of consecutive days with at least one tool call. */
  used_every_day_since: string | null;
  today_utc: string;
  includes_our_own_traffic: true;
  source: string;
}

export interface AgentStats {
  total_paid_calls: number;
  total_unique_agents: number;
  total_usdc_earned: number;
  /** External payers only: the wallets listed in promise P2 are excluded. */
  organic: Split & OrganicRecent;
  /** The share generated by the internal wallets, declared rather than hidden. */
  internal: Split;
  our_wallets_source: string;
  last_payment_at: string | null;
  /** External paid calls since 00:00 UTC, so it matches the UTC day of the MCP counter. */
  organic_paid_today_utc?: number;
  /** Null when the MCP counter could not be read: the page then shows a dash, never a zero. */
  free_mcp?: FreeMcpUsage | null;
}

const EMPTY_SPLIT: Split = { paid_calls: 0, unique_agents: 0, usdc: 0 };
const EMPTY_STATS: AgentStats = {
  total_paid_calls: 0,
  total_unique_agents: 0,
  total_usdc_earned: 0,
  organic: { ...EMPTY_SPLIT, last_payment_at: null, payment_times_48h: [] },
  internal: EMPTY_SPLIT,
  our_wallets_source: 'https://gblin.digital/promises/P2-honest-counters.json',
  last_payment_at: null,
};

// Attribution block — additive, consumed by third parties that cite this data.
const SOURCE = {
  name: 'GBLIN Agent Economy Observatory',
  url: 'https://gblin.digital/observatory',
  data_endpoint: 'https://gblin.digital/api/agent-stats',
  docs: 'https://gblin.digital/llms.txt',
  license: "CC BY 4.0 — cite 'GBLIN Agent Economy Observatory'",
  disclosure:
    'GBLIN operates paid x402 endpoints. Per promise P2, total_* counters are cumulative since launch and include payments made by our own wallets; the `organic` block excludes them, using the wallet list published in P2. organic.last_payment_at and organic.payment_times_48h (times only, no addresses) back the last call and today figures on the home page. free_mcp is read from the public counter of the hosted MCP server: tool calls (not session handshakes), UTC days, our own checks included because that counter has no caller identity. Methodology is public.',
} as const;

const MCP_USAGE_URL = 'https://gblin-mcp.gblin-mcp-worker.workers.dev/mcp/usage?days=60';

async function fetchFreeMcp(): Promise<FreeMcpUsage | null> {
  try {
    const res = await fetch(MCP_USAGE_URL, { signal: AbortSignal.timeout(5000), cache: 'no-store' });
    if (!res.ok) return null;
    const body = (await res.json()) as { daily?: Array<{ day: string; calls: Record<string, number> }> };
    const daily = Array.isArray(body.daily) ? body.daily : [];
    if (daily.length === 0) return null;
    const use = (c: Record<string, number>) =>
      Object.entries(c).reduce(
        (sum, [k, n]) => (k.startsWith('tools/call') || k === 'resources/read' || k === 'prompts/get' ? sum + (Number(n) || 0) : sum),
        0,
      );
    const today = new Date().toISOString().slice(0, 10);
    const byDay = new Map(daily.map((d) => [d.day, d.calls ?? {}]));
    // Consecutive UTC days with at least one call, walking back from yesterday (today is still running).
    let since: string | null = null;
    for (let i = 1; i < 400; i++) {
      const day = new Date(Date.now() - i * 86_400_000).toISOString().slice(0, 10);
      const calls = byDay.get(day);
      if (!calls || use(calls) === 0) break;
      since = day;
    }
    const todayCalls = byDay.get(today) ?? {};
    return {
      tool_calls_total: daily.reduce((sum, d) => sum + use(d.calls ?? {}), 0),
      tool_calls_today: use(todayCalls),
      sessions_today: Number(todayCalls['initialize'] ?? 0),
      counted_since: daily[daily.length - 1].day,
      used_every_day_since: since,
      today_utc: today,
      includes_our_own_traffic: true,
      source: 'https://gblin-mcp.gblin-mcp-worker.workers.dev/mcp/usage',
    };
  } catch {
    return null;
  }
}

async function fetchAgentStats(): Promise<AgentStats> {
  const payments = await inboundTokenPayments(FEE_WALLET, USDC_BASE);

  const agents = { all: new Set<string>(), organic: new Set<string>(), internal: new Set<string>() };
  let totalMicro = 0n;
  let organicMicro = 0n;
  let internalMicro = 0n;
  let organicCalls = 0;
  let internalCalls = 0;
  let lastAt: string | null = null;
  let organicLastAt: string | null = null;
  const organicRecent: string[] = [];
  const since48h = Date.now() - 48 * 3_600_000;

  for (const p of payments) {
    // A transfer from the fee wallet to itself is not a payment received.
    if (p.from === FEE_WALLET.toLowerCase()) continue;

    let micro = 0n;
    try {
      micro = BigInt(p.value);
    } catch {
      // malformed value: the call still counts, the amount does not
    }

    agents.all.add(p.from);
    totalMicro += micro;
    if (p.timestamp && (!lastAt || p.timestamp > lastAt)) lastAt = p.timestamp;

    if (OUR_WALLETS.has(p.from)) {
      agents.internal.add(p.from);
      internalCalls += 1;
      internalMicro += micro;
    } else {
      agents.organic.add(p.from);
      organicCalls += 1;
      organicMicro += micro;
      if (p.timestamp) {
        if (!organicLastAt || p.timestamp > organicLastAt) organicLastAt = p.timestamp;
        if (Date.parse(p.timestamp) >= since48h) organicRecent.push(p.timestamp);
      }
    }
  }

  const usdc = (v: bigint) => Number(v) / 1e6;

  return {
    total_paid_calls: organicCalls + internalCalls,
    total_unique_agents: agents.all.size,
    total_usdc_earned: usdc(totalMicro),
    organic: {
      paid_calls: organicCalls,
      unique_agents: agents.organic.size,
      usdc: usdc(organicMicro),
      last_payment_at: organicLastAt,
      payment_times_48h: organicRecent.sort().reverse(),
    },
    internal: {
      paid_calls: internalCalls,
      unique_agents: agents.internal.size,
      usdc: usdc(internalMicro),
    },
    our_wallets_source: 'https://gblin.digital/promises/P2-honest-counters.json',
    last_payment_at: lastAt,
    organic_paid_today_utc: organicRecent.filter((t) => t.slice(0, 10) === new Date().toISOString().slice(0, 10)).length,
    free_mcp: await fetchFreeMcp(),
  };
}

export async function GET(): Promise<Response> {
  const now = Date.now();
  if (cache && now - cache.fetchedAt < CACHE_TTL_MS) {
    return Response.json(
      { ...cache.data, _source: SOURCE },
      { headers: { 'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=900' } },
    );
  }

  try {
    const data = await fetchAgentStats();
    cache = { data, fetchedAt: now };
    return Response.json(
      { ...data, _source: SOURCE },
      { headers: { 'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=900' } },
    );
  } catch (err) {
    // Never a 500: the home page has to render. The previous cache is served
    // when there is one, otherwise zeros DECLARED as such — a zero must never
    // be readable as "nobody paid".
    const fallback = cache?.data ?? EMPTY_STATS;
    cache = { data: fallback, fetchedAt: now - (CACHE_TTL_MS - ERROR_CACHE_TTL_MS) };
    return Response.json(
      {
        ...fallback,
        stale: true,
        error: redactSecrets((err as Error).message),
        _source: SOURCE,
      },
      { headers: { 'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=300' } },
    );
  }
}
