/**
 * GET /api/agent-stats
 *
 * Counters of the x402 payments received by the fee wallet, for the "AI Agents"
 * section.
 *
 * Source: asset transfers read from the chain — see src/lib/chain-activity.ts.
 *
 * WHAT IS COUNTED, AND WHY THERE ARE TWO NUMBERS
 * Promise P2 (hash-pinned, public/promises/P2-honest-counters.json) states that
 * the public counters are CUMULATIVE SINCE LAUNCH and INCLUDE the operator's own
 * wallets, and that the list of those wallets is published so that a third party
 * can reproduce the split between internal and external activity. Therefore:
 *   - `total_*` stays cumulative and includes the internal wallets: changing it
 *     would falsify a promise already anchored on-chain (it would require a P2
 *     v2 with a new promiseId).
 *   - `organic` is that split, computed here instead of left to the reader.
 * The list of internal wallets is read FROM THE PROMISE FILE rather than copied:
 * one single source, and the counts follow the file if it changes.
 */

import { inboundTokenPayments, USDC_BASE, FEE_WALLET } from '@/lib/chain-activity';
import promise from '../../../../public/promises/P2-honest-counters.json';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const OUR_WALLETS = new Set(
  (promise.our_wallets ?? []).map((w: string) => w.toLowerCase()),
);

// ─── In-memory cache ─────────────────────────────────────────────────────────
const CACHE_TTL_MS = 5 * 60 * 1_000;
const ERROR_CACHE_TTL_MS = 30_000;
let cache: { data: AgentStats; fetchedAt: number } | null = null;

interface Split {
  paid_calls: number;
  unique_agents: number;
  usdc: number;
}

export interface AgentStats {
  total_paid_calls: number;
  total_unique_agents: number;
  total_usdc_earned: number;
  /** External payers only: the wallets listed in promise P2 are excluded. */
  organic: Split;
  /** The share generated by the internal wallets, declared rather than hidden. */
  internal: Split;
  our_wallets_source: string;
  last_payment_at: string | null;
}

const EMPTY_SPLIT: Split = { paid_calls: 0, unique_agents: 0, usdc: 0 };
const EMPTY_STATS: AgentStats = {
  total_paid_calls: 0,
  total_unique_agents: 0,
  total_usdc_earned: 0,
  organic: EMPTY_SPLIT,
  internal: EMPTY_SPLIT,
  our_wallets_source: 'https://gblin.digital/promises/P2-honest-counters.json',
  last_payment_at: null,
};

// Attribution block — additive, consumed by third parties that cite this data.
const SOURCE = {
  name: 'GBLIN Agent Economy Observatory',
  url: 'https://gblin.digital/observatory',
  data_endpoint: 'https://gblin.digital/api/agent-stats',
  docs: 'https://gblin.digital/llms.txt',
  license: "CC BY 4.0 — cite 'GBLIN Agent Economy Observatory'",
  disclosure:
    'GBLIN operates paid x402 endpoints. Per promise P2, total_* counters are cumulative since launch and include payments made by our own wallets; the `organic` block excludes them, using the wallet list published in P2. Methodology is public.',
} as const;

async function fetchAgentStats(): Promise<AgentStats> {
  const payments = await inboundTokenPayments(FEE_WALLET, USDC_BASE);

  const agents = { all: new Set<string>(), organic: new Set<string>(), internal: new Set<string>() };
  let totalMicro = 0n;
  let organicMicro = 0n;
  let internalMicro = 0n;
  let organicCalls = 0;
  let internalCalls = 0;
  let lastAt: string | null = null;

  for (const p of payments) {
    // A transfer from the fee wallet to itself is not a payment received.
    if (p.from === FEE_WALLET.toLowerCase()) continue;

    let micro = 0n;
    try {
      micro = BigInt(p.value);
    } catch {
      // malformed value: the call still counts, the amount does not
    }

    agents.all.add(p.from);
    totalMicro += micro;
    if (p.timestamp && (!lastAt || p.timestamp > lastAt)) lastAt = p.timestamp;

    if (OUR_WALLETS.has(p.from)) {
      agents.internal.add(p.from);
      internalCalls += 1;
      internalMicro += micro;
    } else {
      agents.organic.add(p.from);
      organicCalls += 1;
      organicMicro += micro;
    }
  }

  const usdc = (v: bigint) => Number(v) / 1e6;

  return {
    total_paid_calls: organicCalls + internalCalls,
    total_unique_agents: agents.all.size,
    total_usdc_earned: usdc(totalMicro),
    organic: {
      paid_calls: organicCalls,
      unique_agents: agents.organic.size,
      usdc: usdc(organicMicro),
    },
    internal: {
      paid_calls: internalCalls,
      unique_agents: agents.internal.size,
      usdc: usdc(internalMicro),
    },
    our_wallets_source: 'https://gblin.digital/promises/P2-honest-counters.json',
    last_payment_at: lastAt,
  };
}

export async function GET(): Promise<Response> {
  const now = Date.now();
  if (cache && now - cache.fetchedAt < CACHE_TTL_MS) {
    return Response.json(
      { ...cache.data, _source: SOURCE },
      { headers: { 'Cache-Control': 'public, s-maxage=1800, stale-while-revalidate=3600' } },
    );
  }

  try {
    const data = await fetchAgentStats();
    cache = { data, fetchedAt: now };
    return Response.json(
      { ...data, _source: SOURCE },
      { headers: { 'Cache-Control': 'public, s-maxage=1800, stale-while-revalidate=3600' } },
    );
  } catch (err) {
    // Never a 500: the home page has to render. The previous cache is served
    // when there is one, otherwise zeros DECLARED as such — a zero must never
    // be readable as "nobody paid".
    const fallback = cache?.data ?? EMPTY_STATS;
    cache = { data: fallback, fetchedAt: now - (CACHE_TTL_MS - ERROR_CACHE_TTL_MS) };
    return Response.json(
      {
        ...fallback,
        stale: true,
        error: (err as Error).message,
        _source: SOURCE,
      },
      { headers: { 'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=300' } },
    );
  }
}
